// <auto-generated />
namespace MEAClosedLoop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class creation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(creation));
        
        string IMigrationMetadata.Id
        {
            get { return "201405201447452_creation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
